# Generated by Django 5.0.3 on 2024-05-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookstable_is_availabe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstable',
            name='category',
            field=models.CharField(choices=[('Novel', 'Novel'), ('Story', 'Story'), ('Comic', 'Comic'), ('Historical', 'Historical')], max_length=100),
        ),
    ]
