# Generated by Django 5.0.3 on 2024-05-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bookstable_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstable',
            name='author',
        ),
        migrations.AddField(
            model_name='bookstable',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookstable',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bookstable',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
