# Generated by Django 5.0.3 on 2024-05-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookstable_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookstable',
            old_name='is_availabe',
            new_name='is_available',
        ),
        migrations.AlterField(
            model_name='bookstable',
            name='category',
            field=models.CharField(choices=[('novel', 'Novel'), ('story', 'Story'), ('comic', 'Comics'), ('historical', 'Historical')], max_length=100),
        ),
    ]
