# Generated by Django 5.0.3 on 2024-05-31 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_is_availabe_bookstable_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='address',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='pincode',
        ),
    ]
