# Generated by Django 5.0.3 on 2024-06-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_carttable_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
